"""add_telemetry

Revision ID: 1f6ec311d762
Revises: a07f99fc0ca8
Create Date: 2026-07-05 16:54:17.868061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f6ec311d762'
down_revision: Union[str, None] = 'a07f99fc0ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dlq_queue_failed'), table_name='dead_letter_queue')
    op.create_index('idx_dlq_queue_failed', 'dead_letter_queue', ['queue_id', 'failed_at'], unique=False, postgresql_ops={'failed_at': 'DESC'})
    op.drop_index(op.f('idx_jobs_claim'), table_name='jobs')
    op.create_index('idx_jobs_claim', 'jobs', ['queue_id', 'status', 'priority', 'run_at'], unique=False, postgresql_ops={'priority': 'DESC'})
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('worker_heartbeats', sa.Column('cpu_percent', sa.Float(), nullable=True))
    op.add_column('worker_heartbeats', sa.Column('ram_mb', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_heartbeats_worker_ts'), table_name='worker_heartbeats')
    op.create_index('idx_heartbeats_worker_ts', 'worker_heartbeats', ['worker_id', 'ts'], unique=False, postgresql_ops={'ts': 'DESC'})
    op.drop_column('worker_heartbeats', 'mem_mb')
    op.drop_column('worker_heartbeats', 'cpu_pct')
    op.add_column('workers', sa.Column('cpu_percent', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('ram_mb', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'ram_mb')
    op.drop_column('workers', 'cpu_percent')
    op.add_column('worker_heartbeats', sa.Column('cpu_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('worker_heartbeats', sa.Column('mem_mb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('idx_heartbeats_worker_ts', table_name='worker_heartbeats', postgresql_ops={'ts': 'DESC'})
    op.create_index(op.f('idx_heartbeats_worker_ts'), 'worker_heartbeats', ['worker_id', sa.literal_column('ts DESC')], unique=False)
    op.drop_column('worker_heartbeats', 'ram_mb')
    op.drop_column('worker_heartbeats', 'cpu_percent')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_jobs_claim', table_name='jobs', postgresql_ops={'priority': 'DESC'})
    op.create_index(op.f('idx_jobs_claim'), 'jobs', ['queue_id', 'status', sa.literal_column('priority DESC'), 'run_at'], unique=False)
    op.drop_index('idx_dlq_queue_failed', table_name='dead_letter_queue', postgresql_ops={'failed_at': 'DESC'})
    op.create_index(op.f('idx_dlq_queue_failed'), 'dead_letter_queue', ['queue_id', sa.literal_column('failed_at DESC')], unique=False)
    # ### end Alembic commands ###
